version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.3
  shellcheck: circleci/shellcheck@3.4

filters: &filters
  tags:
    only: /.*/

jobs:
  test-tag-selection:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Run tag selection tests
          command: bash test/generate_tags_test.sh

workflows:
  lint-pack:
    jobs:
      - test-tag-selection:
          filters: *filters
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: container-tagger-orb
          requires: [test-tag-selection, orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
